### ISSUE TITLE
Points are not being validated correctly

### ISSUE THREAD

**Issue by Rumpelstinsk** [jazzband/geojson#143]
Check the code snippet. When you initialize a point using coordinates for a line, it says is a valid point:

```
import geojson

lineCoords=[[1,2],[3,4]]
pointCoords=[5,6]

print ("Line(lineCoords): ", geojson.LineString(lineCoords).is_valid)
print ("Line(pointCoors): ", geojson.LineString(pointCoords).is_valid)
print ("Point(pointCoords): ", geojson.Point(pointCoords).is_valid)
print ("Point(lineCoords): ", geojson.Point(lineCoords).is_valid)
```

Which produces the next exit:

> Line(lineCoords):  True
> Line(pointCoors):  False
> Point(pointCoords):  True
> Point(lineCoords):  True

Initializing a Point using coordinates for a  line should returns an invalid point.
According to Apendix A.1 of [RFC 7946](https://tools.ietf.org/rfc/rfc7946.txt)

> Point coordinates are in x, y order (easting, northing for projected
   coordinates, longitude, and latitude for geographic coordinates)

So, only an array of two numbers shold be considered as valid.

**Comment by Rumpelstinsk** [comment]
I have taken a look to geometry code. I think it can be resolved, with this change.
Instead of:
```python
def check_point(coord):
    if not isinstance(coord, list):
        return 'each position must be a list'
    if len(coord) not in (2, 3):
        return 'a position must have exactly 2 or 3 values'
```

Do:
```python
import numbers

def check_point(coord):
    if not isinstance(coord, list):
        return 'each position must be a list'
    if len(coord) not in (2, 3):
        return 'a position must have exactly 2 or 3 values'
    for number in coord:
        if not isinstance(number, numbers.Number):
               return 'a position cannot have inner positions'
```

I assume the third coordinadate are for 3d. But i think RFC 7946 only supports 2D

**Comment by auvipy** [comment]
can you come with a PR?

**Comment by Rumpelstinsk** [comment]
@auvipy No problem. I have just made a pull request.

**Comment by Rumpelstinsk** [comment]
I saw the pull request was merged. I assume it will be available in the next release, so I close the issue
