### ISSUE TITLE
Reduce resoloution of GeoJSON object [feature request]

### ISSUE THREAD

**Issue by Tasty213** [jazzband/geojson#158]
Hi,
I have a GeoJSON polygon that's made of 67,077 points. It's far too long to be used with the API of the website I'm trying to communicate with. It would be really useful if there was a function to reduce the resolution of the polygon.

**Comment by TheGreatRefrigerator** [comment]
Hi @Tasty213,
i'm not one of the package managers and didn't work with this package yet, but am working on a very simliar thing right now.
There are several simplification algorithms already implemented in different packages, e.g. https://pypi.org/project/rdp/ for
douglas-peucker which you might be able to use with the provided mapping functionality (maybe..)

What i didn't come across yet, but would also be beneficial for large polygons, is a representation similar to the google encoded polyline. It can be easily used with normal LineStrings and simple Polygons, but not on any GeoJSON as a whole :/

Well hope the simplification might help in your case
cheers

**Comment by rayrrr** [comment]
Thanks for the tip @TheGreatRefrigerator, I agree that https://github.com/fhirschmann/rdp already handles the use case you're describing, @Tasty213. Can you give that a try and report back?
