### ISSUE TITLE
UTF-8 \u escaping

### ISSUE THREAD

**Issue by Creatium** [jazzband/geojson#163]
While trying to create Features with properties that have UTF-8 characters, they get encoded in to \u strings.

Way to replicate:
- create a` Feature(geometry=point)`
- add a property with UTF-8 characters `feat["properties"]["name"] = ąčęėįį`
- print the result (no dumps, just basic print)

Is this an issue or am I missing something?

**Comment by sackh** [comment]
I am also getting the same issue.
Example:
```
from geojson import Feature, Point

ft = Feature(geometry=Point((17, 73)), properties={"title": 'Invalidenstraße 116, 10115 Berlin, Germany'})
print(ft)
```
output:
```
{"geometry": {"coordinates": [17, 73], "type": "Point"}, "properties": {"title": "Invalidenstra\u00dfe 116, 10115 Berlin, Germany"}, "type": "Feature"}
```

**Comment by rayrrr** [comment]
Thank you for reporting this issue. I have replicated the bug and we are putting a fix in place for this.

**Comment by rayrrr** [comment]
@Creatium and @sackh a fix has been merged to master, please give it a try and confirm if possible, thanks.

**Comment by sackh** [comment]
@rayrrr Thanks for the quick fix, this works!
