### ISSUE TITLE
Subclassing from GeoJSON creates invalid GeoJSON

### ISSUE THREAD

**Issue by devleaks** [jazzband/geojson#178]
Hello,

In base.py/GeoJSON, the line:

`self["type"] = getattr(self, "type", type(self).__name__)`

leads to the creation of invalid GeoJSON in subclassing from GeoJSON.

Here is an illustration:

```
from geojson import Point, Feature

class Vertex(Feature):
    def __init__(self, arr: [float]):
        Feature.__init__(self, geometry=Point(arr))

v = Vertex((1, 2))

print(isinstance(v, Feature), v)
# True {"geometry": {"coordinates": [1, 2], "type": "Point"}, "properties": {}, "type": "Vertex"}
# type="Vertex" is invalid geojson
```

Issue is of course using `type(self).__name__` as a default value.

It is very anoying because [it prevents other packages](https://github.com/omanges/turfpy/issues/97) from not recognizing valid GeoJSON.

P.

**Comment by devleaks** [comment]
Hugly workaround is to insert proper type when subclassing:
```
class Vertex(Feature):
    def __init__(self, arr: [float]):
        self["type"] = "Feature"
        Feature.__init__(self, geometry=Point(arr))
```

**Comment by rayrrr** [comment]
Hi @devleaks thanks for the issue. https://datatracker.ietf.org/doc/html/rfc7946#section-7 states that 

>  GeoJSON Types Are Not Extensible

>   Implementations MUST NOT extend the fixed set of GeoJSON types:
   FeatureCollection, Feature, Point, LineString, MultiPoint, Polygon,
   MultiLineString, MultiPolygon, and GeometryCollection.

**Comment by devleaks** [comment]
Sorry, I think I did not express myself clearly. I don't want to and I do not extend GeoJSON.

We are talking python here. I want to extend a **python** class. Does GeoJSON standard also prevent that??
The problem is that this statement:

`self["type"] = getattr(self, "type", type(self).__name__)`

sets the value of the GeoJSON `type` attribute to the name of any python subclass you may derive from a GeoJSON class, leading to invalid GeoJSON when printed, or when other libraries rely on this `type` attribute and expect a valid GeoJSON type attribute value.

Anyway, the proposed work around (which helps set the type attribute value to a valid GeoJSON value) is ugly but works perfectly. One extra line of code, and a comment with a link towards this issue do the work.

P.
