### ISSUE TITLE
renaming `master` branch to `main`

### ISSUE THREAD

**Issue by rayrrr** [jazzband/geojson#181]
We will soon be renaming the default branch from `master` to `main`, in line with [new repositories created on GitHub](https://github.com/github/renaming). Some ideas how to do this are described [here](https://stevenmortimer.com/5-steps-to-change-github-default-branch-from-master-to-main/) and [here](https://www.hanselman.com/blog/easily-rename-your-git-default-branch-from-master-to-main).

**Comment by jezdez** [comment]
I've renamed the branch and opened #192 to fix some reference to it.

**Comment by hugovk** [comment]
Can I hop on this issue and ask for the same in https://github.com/jazzband/prettytable? Thank you!

**Comment by jezdez** [comment]
@hugovk Done!
