### ISSUE TITLE
Release request to support Python 3.11 patch versions

### ISSUE THREAD

**Issue by apastel** [jazzband/geojson#199]
Hello :)
Our project was encountering the issue with geojson-3.0.0 not supporting Python 3.11 patch versions (currently on Python 3.11.1), and I was happy to see that a commit was made on Feb 4 to support everything up to 3.12.

I know that the geojson 3.0.0 release is pretty new itself (released on Jan 25) but I was wondering if another release could be tagged now that geojson is supporting the Python 3.11 patch releases? 🤞  I see there have been two other fixes since then as well, but supporting Python 3.11 patch versions would help our build succeed again :smiley: 

Just a request! I appreciate the consideration.

**Comment by rayrrr** [comment]
@apastel thanks for the nudge, was planning on this. Done! Now available on PyPI and via `pip install`.
